CLASS zcl_lab_21_classroom_0631 DEFINITION
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_21_classroom_0631 IMPLEMENTATION.
ENDCLASS.
