CLASS zcl_lab_23_company_0631 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
  GLOBAL FRIENDS zcl_lab_24_partner_0631 .

  PUBLIC SECTION.
  PROTECTED SECTION.

  PRIVATE SECTION.

    DATA capital TYPE i value '123456'.

ENDCLASS.


CLASS zcl_lab_23_company_0631 IMPLEMENTATION.
ENDCLASS.
