CLASS zcl_lab_12_linux_0631 DEFINITION INHERITING FROM zcl_lab_11_system_0631
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_12_linux_0631 IMPLEMENTATION.
ENDCLASS.
